### PR TITLE
WIP: Fix windows support

### PR DESCRIPTION
**Pull request by ceremcem**
* Build works correctly, 
* Mocha tests fail with "Can not find file: \\?\C:\Users\cca\Desktop\node-occ\lib\binding\occ.node"

I'm sure mocha tests will pass once it is configured correctly. However, I couldn't figure it out. 

# Testing On Your Side: 

1. `git clone --single-branch --branch fix-windows-support https://github.com/ceremcem/node-occ`
2. Then follow the instructions on: https://github.com/ceremcem/node-occ/tree/fix-windows-support#on-windows

# Related 

#50

### CODE REVIEW

**Comment by erossignon** [comment]
We need to get the unit test working before we could  consider merging

**Comment by ceremcem** [comment]
Of course tests should work. However, I need some help here. I spent a day to set Mocha path, without any success. If you can show me where to set the Mocha search path, I think I could configure it to use relative path rather than an absolute path, which will overcome the problem.

**Comment by erossignon** [comment]
OK don't worry I fix it..

**Comment by erossignon** [comment]
@ceremcem , I think this fix collides with other fixes already made in the same area to improve build on linux and windows.  Do you want to keep this PR active or is it OK o close it?

**Comment by ceremcem** [comment]
It's okay to be closed. My intention was to use same code both Windows and
Linux in node-occ development, however there are pieces I can't make it
fit together. As you say, it's already fixed, so there is no need for this
PR. Thanks for your courtesy.

Etienne <notifications@github.com>, 18 Eyl 2020 Cum, 17:11 tarihinde şunu
yazdı:

**Pull request closed without merging**
